DIR += 	srcs/strings/transform/ \
	srcs/strings/transform/ \
	srcs/strings/transform/ \
	srcs/strings/transform/ \
	srcs/strings/transform/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/search/ \
	srcs/strings/len/ \
	srcs/strings/len/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/duplicate/ \
	srcs/strings/copy/ \
	srcs/strings/copy/ \
	srcs/strings/copy/ \
	srcs/strings/copy/ \
	srcs/strings/copy/ \
	srcs/strings/compare/ \
	srcs/strings/compare/ \
	srcs/strings/compare/ \
	srcs/strings/compare/ 
