SRC += 	ft_strmapi.c \
	ft_strmap.c \
	ft_striteri.c \
	ft_striter.c \
	ft_strclr.c \
	ft_strstr.c \
	ft_strrchr.c \
	ft_strnstr.c \
	ft_strchr.c \
	ft_pstrnstr.c \
	ft_nmatch.c \
	ft_match.c \
	ft_char_srch.c \
	ft_strnlen.c \
	ft_strlen.c \
	ft_toupper.c \
	ft_tolower.c \
	ft_isupper.c \
	ft_isprint.c \
	ft_islower.c \
	ft_isdigit.c \
	ft_isascii.c \
	ft_isalpha.c \
	ft_isalnum.c \
	ft_strsub.c \
	ft_strsplit.c \
	ft_strjoin_multi.c \
	ft_strjoin.c \
	ft_strdup.c \
	ft_strncpy.c \
	ft_strncat.c \
	ft_strlcat.c \
	ft_strcpy.c \
	ft_strcat.c \
	ft_strnequ.c \
	ft_strncmp.c \
	ft_strequ.c \
	ft_strcmp.c \
	.ft_strfastlen.c \
	ft_strtrim.c 
