PAT += 	srcs/strings/transform/ft_strmapi.c \
	srcs/strings/transform/ft_strmap.c \
	srcs/strings/transform/ft_striteri.c \
	srcs/strings/transform/ft_striter.c \
	srcs/strings/transform/ft_strclr.c \
	srcs/strings/search/ft_strstr.c \
	srcs/strings/search/ft_strrchr.c \
	srcs/strings/search/ft_strnstr.c \
	srcs/strings/search/ft_strchr.c \
	srcs/strings/search/ft_pstrnstr.c \
	srcs/strings/search/ft_nmatch.c \
	srcs/strings/search/ft_match.c \
	srcs/strings/search/ft_char_srch.c \
	srcs/strings/len/ft_strnlen.c \
	srcs/strings/len/ft_strlen.c \
	srcs/strings/len/.ft_strfastlen.c \
	srcs/strings/ft_is/ft_toupper.c \
	srcs/strings/ft_is/ft_tolower.c \
	srcs/strings/ft_is/ft_isupper.c \
	srcs/strings/ft_is/ft_isprint.c \
	srcs/strings/ft_is/ft_islower.c \
	srcs/strings/ft_is/ft_isdigit.c \
	srcs/strings/ft_is/ft_isascii.c \
	srcs/strings/ft_is/ft_isalpha.c \
	srcs/strings/ft_is/ft_isalnum.c \
	srcs/strings/duplicate/ft_strtrim.c \
	srcs/strings/duplicate/ft_strsub.c \
	srcs/strings/duplicate/ft_strsplit.c \
	srcs/strings/duplicate/ft_strjoin_multi.c \
	srcs/strings/duplicate/ft_strjoin.c \
	srcs/strings/duplicate/ft_strdup.c \
	srcs/strings/copy/ft_strncpy.c \
	srcs/strings/copy/ft_strncat.c \
	srcs/strings/copy/ft_strlcat.c \
	srcs/strings/copy/ft_strcpy.c \
	srcs/strings/copy/ft_strcat.c \
	srcs/strings/compare/ft_strnequ.c \
	srcs/strings/compare/ft_strncmp.c \
	srcs/strings/compare/ft_strequ.c \
	srcs/strings/compare/ft_strcmp.c 
