PAT += 	srcs/structures/tab/transform/ft_tabiter.c \
	srcs/structures/tab/print/ft_tab_print_one_elmnt.c \
	srcs/structures/tab/print/ft_tab_print_dir.c \
	srcs/structures/tab/move/ft_tab_reach_end.c \
	srcs/structures/tab/move/ft_tab_dirth.c \
	srcs/structures/tab/move/ft_tab_access.c \
	srcs/structures/tab/len/ft_tabloop_lendir.c \
	srcs/structures/tab/len/ft_tab_lendir.c \
	srcs/structures/tab/ft_is/ft_tabloop_itis.c \
	srcs/structures/tab/dir/ft_tab_dir_reverse.c \
	srcs/structures/tab/dir/ft_tab_dir_rclock.c \
	srcs/structures/tab/dir/ft_tab_dir_nclock.c \
	srcs/structures/tab/dir/ft_tab_dir_clock.c \
	srcs/structures/tab/del/ft_tab_delete_row_len.c \
	srcs/structures/tab/del/ft_tab_delete_row.c \
	srcs/structures/tab/create/ft_tabnew_rectangle.c \
	srcs/structures/tab/create/ft_tabnew_ptr.c \
	srcs/structures/tab/create/ft_tabnew_dir.c \
	srcs/structures/tab/create/ft_tab_square_it.c \
	srcs/structures/tab/connect/ft_tabloop_it.c \
	srcs/structures/tab/connect/ft_tabadd_start.c \
	srcs/structures/tab/connect/ft_tabadd_here.c \
	srcs/structures/tab/connect/ft_tabadd_end.c \
	srcs/structures/tab/connect/ft_tabadd.c \
	srcs/structures/tab/connect/ft_tab_cutone.c \
	srcs/structures/tab/connect/ft_tab_cut_loop.c \
	srcs/structures/tab/connect/ft_tab_connect_structs.c \
	srcs/structures/tab/connect/ft_tab_connect_dir.c \
	srcs/structures/list/transform/ft_lstmap.c \
	srcs/structures/list/transform/ft_lstiter.c \
	srcs/structures/list/move/ft_lstfind_th.c \
	srcs/structures/list/move/ft_lst_reach_end.c \
	srcs/structures/list/len/ft_lst_count.c \
	srcs/structures/list/del/ft_lstdelone.c \
	srcs/structures/list/del/ft_lstdel.c \
	srcs/structures/list/del/ft_lst_free.c \
	srcs/structures/list/create/ft_lstnew_ptr.c \
	srcs/structures/list/create/ft_lstnew.c \
	srcs/structures/list/connect/ft_lstcutone.c \
	srcs/structures/list/connect/ft_lstadd_start.c \
	srcs/structures/list/connect/ft_lstadd_here.c \
	srcs/structures/list/connect/ft_lstadd_end.c \
	srcs/structures/list/connect/ft_lstadd.c 
